version: '3.8'

services:
  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    networks:
      - smart-house-network

  # Backend Node.js API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - smart-house-network
    restart: unless-stopped

networks:
  smart-house-network:
    driver: bridge

volumes:
  node_modules:

